name: BlackDuck Scans

on:
  workflow_dispatch:
  schedule:
    # Only run twice a week on default branch (main).
    # BlackDuck has a min-scan-interval of 24h:
    - cron: '40 10 * * 3,5'

jobs:
  scans:
    uses: cap/.github/.github/workflows/scans.yml@9614bc0531fcd635c7ff0935393428a6ae17422f # main
    secrets: inherit
    with:
      project: CDSUMBRELLA