name: BlackDuck Scans

on:
  workflow_dispatch:
  schedule:
    # Only run twice a week on default branch (main).
    # BlackDuck has a min-scan-interval of 24h:
    - cron: '40 10 * * 3,5'

jobs:
  scans:
    uses: cap/.github/.github/workflows/scans.yml@9f7b60fd8374f26f57c64546ea8a82e7e11f6adc # main
    secrets: inherit
    with:
      project: CDSUMBRELLA