name: BlackDuck Scans

on:
  workflow_dispatch:
  schedule:
    # Only run twice a week on default branch (main).
    # BlackDuck has a min-scan-interval of 24h:
    - cron: '40 10 * * 3,5'

jobs:
  scans:
    uses: cap/.github/.github/workflows/scans.yml@ffc33468176cbd4763d8d1e2556a2dfa0ae55a06 # main
    secrets: inherit
    with:
      project: CDSUMBRELLA