name: Check Changelog
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]
    branches:
      - main
jobs:
  Check-Changelog:
    name: Check Changelog Action
    runs-on: [self-hosted, solinas]
    steps:
      - name: Check changelog
        uses: cap/.github/.github/actions/check-changelog@ffc33468176cbd4763d8d1e2556a2dfa0ae55a06 # main
