name: Check Changelog
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]
    branches:
      - main
jobs:
  Check-Changelog:
    name: Check Changelog Action
    runs-on: [self-hosted, solinas]
    steps:
      - name: Check changelog
        uses: cap/.github/.github/actions/check-changelog@9f7b60fd8374f26f57c64546ea8a82e7e11f6adc # main
