name: Check PR Title
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  Check-PR-Title:
    name: Validate PR Title
    runs-on: [self-hosted, solinas]
    steps:
      - name: Check PR title
        uses: cap/.github/.github/actions/check-pr-title@9f7b60fd8374f26f57c64546ea8a82e7e11f6adc # main
