name: Check PR Title
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  Check-PR-Title:
    name: Validate PR Title
    runs-on: [self-hosted, solinas]
    steps:
      - name: Check PR title
        uses: cap/.github/.github/actions/check-pr-title@ffc33468176cbd4763d8d1e2556a2dfa0ae55a06 # main
