name: Create Github Release

on:
  push:
    tags:
      - 'rel/*'

jobs:
  create-github-release:
    uses: cap/.github/.github/workflows/create-gh-release.yml@9f7b60fd8374f26f57c64546ea8a82e7e11f6adc # main
    secrets: inherit
