name: Create Github Release

on:
  push:
    tags:
      - 'rel/*'

jobs:
  create-github-release:
    uses: cap/.github/.github/workflows/create-gh-release.yml@ffc33468176cbd4763d8d1e2556a2dfa0ae55a06 # main
    secrets: inherit
