name: Create Github Release

on:
  push:
    tags:
      - 'rel/*'

jobs:
  create-github-release:
    uses: cap/.github/.github/workflows/create-gh-release.yml@2aa3675d385e2dbdc1ff7838f8fa22b4735b134c # main
    secrets: inherit
