name: Metadata Validatior

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validation:
    name: MCP Server Card
    runs-on: [self-hosted, solinas]
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
      - run: npm i -g @sap/cds-dk
      - run: npm i
      - run: cd tests/bookshop && cds compile ./srv -s CatalogService -2 mcp > server-card.json
      - name: Run API Metadata Validator
        uses: CPA/api-metadata-validator@0b8bb56e19b3350085be75fd7bff07e9342eee44 # main
        with:
          files: ./tests/bookshop/*-card.json
          verbose: true
          only-changed-files: false
